ExamBuilder: NumQuestion.java NumAnswer.java Question.java MCQuestion.java MCSAQuestion.java MCMAQuestion.java SAQuestion.java Answer.java MCAnswer.java MCMAAnswer.java MCSAAnswer.java SAAnswer.java Exam.java ExamBuilder.java
	javac *.java

ExamGrader: NumQuestion.java NumAnswer.java Question.java MCQuestion.java MCSAQuestion.java MCMAQuestion.java SAQuestion.java Answer.java MCAnswer.java MCMAAnswer.java MCSAAnswer.java SAAnswer.java Exam.java ExamGrader.java
	javac *.java

ExamTaker: NumQuestion.java NumAnswer.java Question.java MCQuestion.java MCSAQuestion.java MCMAQuestion.java SAQuestion.java Answer.java MCAnswer.java MCMAAnswer.java MCSAAnswer.java SAAnswer.java Exam.java ExamTaker.java
	javac *.java

clean:
	rm *.class
